image:
  name: metanorma/mn
  entrypoint: [""]

cache:
  paths:

build:
  stage: build
  script:
    - bundle install
    - make clean all
    - make published
    - mv published public
  artifacts:
    paths:
      - public

pages:
  dependencies:
    - build
  stage: deploy
  script:
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=build"'
  artifacts:
    paths:
      - public
  only:
    - master
